"""Generate ``source.sh`` snippets that load (compiler, cost-model,
math, cpu) into env vars.

Pattern: a downstream build can ``source ./source.sh`` and pick up
``CXX``, ``CXX_COSTMODEL``, ``EXTRA_FLAGS``, ``LINK_FLAGS``, plus a
banner identifying the combination. The legacy ``compiler_config.py``
honours ``CXX`` / ``EXTRA_FLAGS`` so the generated file plugs in
without further changes.
"""
from __future__ import annotations

import pathlib
import textwrap
from typing import Optional

from .flags import Compiler, CostModel, FlagSet, get_flags

_BANNER_TEMPLATE = """# -----------------------------------------------------------------------------
# VectraArtifacts source.sh -- compiler={compiler} cost_model={cost_model} math={math} cpu={cpu}
# Rationale: {rationale}
# Generated by ``vectra_artifacts.compilers.source_sh.source_sh``.
# Source this file from a bench script::
#
#     source ./source.sh
#     make
#
# Honoured downstream by compiler_config.py / vectra_artifacts.compilers
# via env vars CXX, EXTRA_FLAGS, LINK_FLAGS, CXX_COSTMODEL.
# -----------------------------------------------------------------------------
"""


def source_sh(flag_set: Optional[FlagSet] = None,
              *,
              compiler: Optional[Compiler] = None,
              cost_model: Optional[CostModel] = None,
              math: bool = False,
              cpu: Optional[str] = None) -> str:
    """Return the text of a ``source.sh`` snippet for the given combo.

    Same two call styles as :func:`configure_dace`. The output is plain
    POSIX shell, safe to source under bash/zsh/dash.
    """
    if flag_set is None:
        if compiler is None or cost_model is None:
            raise TypeError("source_sh requires either flag_set or both compiler+cost_model")
        flag_set = get_flags(compiler, cost_model, math=math, cpu=cpu)

    banner = _BANNER_TEMPLATE.format(
        compiler=flag_set.compiler.value,
        cost_model=flag_set.cost_model.value,
        math="yes" if flag_set.math else "no",
        cpu=flag_set.cpu or "(unspecified)",
        rationale=flag_set.rationale,
    )
    body = textwrap.dedent(f"""\
        export CXX={flag_set.compiler.executable()!r}
        export CXX_COMPILER={flag_set.compiler.value!r}
        export CXX_COSTMODEL={flag_set.cost_model.value!r}
        export CXX_MATH={"1" if flag_set.math else "0"!r}
        export CPU_NAME={flag_set.cpu or ""!r}

        # EXTRA_FLAGS is appended verbatim by compiler_config.py /
        # vectra_artifacts.compilers; it carries the cost-model delta,
        # the optional math-call vector flags, and any caller-supplied
        # extras. Strip the baseline (-O3, -ffast-math, ...) that
        # compiler_config already injects.
        export EXTRA_FLAGS={flag_set.compile_flag_str()!r}

        export LINK_FLAGS={flag_set.link_flag_str()!r}
        """)
    return banner + body


def write_source_sh(target: pathlib.Path, flag_set: Optional[FlagSet] = None, **kwargs) -> pathlib.Path:
    """Write the snippet to ``target`` and return the path. Marks the
    file executable so ``./source.sh`` works too (sourcing doesn't
    require it, but it's conventional)."""
    text = source_sh(flag_set, **kwargs)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    target.chmod(0o755)
    return target
