# -----------------------------------------------------------------------------
# VectraArtifacts source.sh -- compiler=gcc cost_model=unlimited math=no cpu=arm_grace
# Rationale: GCC -ftree-vectorize -ftree-slp-vectorize -fvect-cost-model=unlimited; vectorise whenever physically possible, profitability ignored.
# Generated by ``vectra_artifacts.compilers.source_sh.source_sh``.
# Source this file from a bench script::
#
#     source ./source.sh
#     make
#
# Honoured downstream by compiler_config.py / vectra_artifacts.compilers
# via env vars CXX, EXTRA_FLAGS, LINK_FLAGS, CXX_COSTMODEL.
# -----------------------------------------------------------------------------
export CXX='g++'
export CXX_COMPILER='gcc'
export CXX_COSTMODEL='unlimited'
export CXX_MATH='0'
export CPU_NAME='arm_grace'

# EXTRA_FLAGS is appended verbatim by compiler_config.py /
# vectra_artifacts.compilers; it carries the cost-model delta,
# the optional math-call vector flags, and any caller-supplied
# extras. Strip the baseline (-O3, -ffast-math, ...) that
# compiler_config already injects.
export EXTRA_FLAGS='-O3 -std=c++17 -fPIC -fno-math-errno -ffinite-math-only -fno-signaling-nans -fstrict-aliasing -faligned-new -fopenmp -march=native -ftree-vectorize -fvect-cost-model=unlimited'

export LINK_FLAGS='-shared -fopenmp'
