# -----------------------------------------------------------------------------
# VectraArtifacts source.sh -- compiler=clang cost_model=default math=no cpu=arm_grace
# Rationale: Clang -O3 baseline; paper Table 2 Default row + artifact additions.
# Generated by ``vectra_artifacts.compilers.source_sh.source_sh``.
# Source this file from a bench script::
#
#     source ./source.sh
#     make
#
# Honoured downstream by compiler_config.py / vectra_artifacts.compilers
# via env vars CXX, EXTRA_FLAGS, LINK_FLAGS, CXX_COSTMODEL.
# -----------------------------------------------------------------------------
export CXX='clang++'
export CXX_COMPILER='clang'
export CXX_COSTMODEL='default'
export CXX_MATH='0'
export CPU_NAME='arm_grace'

# EXTRA_FLAGS is appended verbatim by compiler_config.py /
# vectra_artifacts.compilers; it carries the cost-model delta,
# the optional math-call vector flags, and any caller-supplied
# extras. Strip the baseline (-O3, -ffast-math, ...) that
# compiler_config already injects.
export EXTRA_FLAGS='-O3 -std=c++17 -fPIC -fno-math-errno -ffinite-math-only -fno-signaling-nans -fstrict-aliasing -faligned-new -Xclang -fopenmp -I/opt/homebrew/opt/libomp/include -march=native'

export LINK_FLAGS='-shared -L/opt/homebrew/opt/libomp/lib -lomp'
